//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnesClubApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int SaleCode { get; set; }
        public System.DateTime SaleDate { get; set; }
        public int IdAbonement { get; set; }
        public int IdClient { get; set; }
    
        public virtual Abonement Abonement { get; set; }
        public virtual Clients Clients { get; set; }
    }
}
